# Generated by Django 5.0.4 on 2024-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="category_id",
            field=models.IntegerField(default=1, verbose_name="category_id"),
            preserve_default=False,
        ),
    ]
