# Generated by Django 5.0.4 on 2024-04-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_topic_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="quiz.topic"
            ),
        ),
    ]
